Feature/oruk error banner
WeAreSnook/OR-UK-frontend pull request #276
Opened 2021-08-18 12:44 UTC by h0usemaintenance

2021-08-18 16:00 UTC, yemijaiyeola requested changes
Contentconsumer and datafetch, I think still logging to console
<img width="571" alt="Screenshot 2021-08-18 at 16 59 31" src="https://user-images.githubusercontent.com/77054672/129931867-45186b15-6bce-4aa4-8f64-d59c42f8f37c.png">

2021-08-18 16:00 UTC, yemijaiyeola commented on src/components/banner/ErrorFallback.js
> +  );
Cool.  We are not using error prop at the moment.  But will be used server side to write error to log.

2021-08-18 16:00 UTC, yemijaiyeola commented on src/App.js
> +            }).catch(err => console.log("An exception occurred ", err));
we don't want to write "err" to the browser console here.  we use err server side to log to file

2021-08-19 08:45 UTC, h0usemaintenance commented on src/components/banner/ErrorFallback.js
> +  );
Yes, i left it unused following our discussion a few days ago.

2021-08-19 09:17 UTC, h0usemaintenance commented on src/App.js
> +            }).catch(err => console.log("An exception occurred ", err));
The error has been returned instead of logging it in App.js. The contentConsumer and datafetch files have been cleaned as well.

2021-08-19 14:54 UTC, h0usemaintenance commented on src/App.js
> +            }).catch(err => console.log("An exception occurred ", err));
The return statements added above have been reverted to console logs following our discussion earlier as there is currently no process to consume/ action the error(s) returned.

2021-08-19 18:34 UTC, yemijaiyeola approved these changes

2021-08-24 09:32 UTC, merged