Code Clean Up
WeAreSnook/OR-UK-frontend pull request #6
Opened 2021-04-01 13:21 UTC by kingdomlevel

This PR's main purpose is to tidy up the code and put us in a better place moving forwards with development of the react app.

In this feature:

- removes jQuery as a dependency
- removes bootstrap as a dependency and references to it in the JSX code
- removes almost all styling to give us a "blank slate" to work from in working towards Ananda's design
- brings in the start of react-router-dom (not intended behaviour, but it was a place to start from today!)

2021-04-01 13:38 UTC, endyranaudo approved these changes
All good and clear

2021-04-01 15:56 UTC, yemijaiyeola requested changes
Thanks for this.  Looks good.  Only one comment to fix the BASE_URL text.  

Needs refactoring just tidy up but we can do that as a separate PR.  If we just fix the env var then we can push through.

2021-04-01 15:56 UTC, yemijaiyeola commented on src/App.js
> -  const BASE_URL = 'http://54.78.155.180:1337'
let's set as env var

2021-04-01 18:20 UTC, yemijaiyeola reviewed
add tests

2021-04-08 14:17 UTC, yemijaiyeola commented
@kingdomlevel  .I have used this as the basis for the basic-structure and footer pr.  Will continue to evolve. 💯

2021-04-08 17:33 UTC, merged